### ISSUE TITLE
403 error on accessing Julia versions.json

### ISSUE THREAD

**Issue by pberi** [JuliaLang/www.julialang.org#1751]
**Describe the bug**
This issue happens when installing Julia on a cluster in Google Dataproc. We have a scheduled process running everyday in Airflow which creates a cluster in Dataproc, runs the Python process, outputs data, and kills the cluster. The Python process calls a Julia module. If Julia is not installed on the cluster, it is installed via the juliacall package. During the installation, the package tries to access this URL: https://julialang-s3.julialang.org/bin/versions.json to install a specific version, 1.6.7 in our case.

The URL returned a 403 forbidden error on 9th and 10th of September at ~6.45 AM (CEST) due to some reason and it caused an outage in our process. We didn't face this issue when trying to access the URL manually in the browser, however it occurred every time during those two days on running it in the cluster. As of now, the issue seems to be gone but we fear it might happen again since we don't know the cause. Can someone shed some light into why this could be happening?

**Expected behaviour**
The URL should return a 200 response and not throw a 403 error. 

**Environment:**
 - Google Dataproc cluster
 - Machine type: c2d-highcpu-112
 - Image version: 2.0

**Comment by DilumAluthge** [comment]
There was an issue with our GCP mirror. @staticfloat fixed it by disabling the GCP mirror, so those requests should go directly to S3 instead.

**Comment by pberi** [comment]
Thanks @DilumAluthge ! I will look further into this. Just to understand the cause, is it that Google somehow blocks these kinds of requests via the GCP mirror? I don't know anything about how their mirrors work so I'm just speculating.

**Comment by pberi** [comment]
Here's some additional information:
- Python version: 3.8
- juliacall version: latest stable version (0.9.6)

Here's the traceback of the error: 

<pre><code>2022-09-10 04:42:24,389 | INFO     | replenishment_policy.julia.julia:__init__:58 - Initializing Julia Runtime! This should only happen once
2022-09-10 04:42:24,389 | INFO     | replenishment_policy.julia.julia:__init__:61 - Also installing Julia itself and the required dependencies
[juliapkg] Locating Julia =1.6.7
[juliapkg] Querying Julia versions from https://julialang-s3.julialang.org/bin/versions.json
Traceback (most recent call last):
  File "/tmp/replenishment-policy-parameters_1f30da4c/cli.py", line 71, in <module>
    cli()
  File "/opt/conda/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/default/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/default/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/default/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/default/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/replenishment-policy-parameters_1f30da4c/cli.py", line 67, in calculate
    run(project=project, run_date=run_date)
  File "/opt/conda/default/lib/python3.8/site-packages/coolblue/monitoring/monitoring.py", line 225, in wrapper
    result = func(*args, **kwargs)
  File "/opt/conda/default/lib/python3.8/site-packages/replenishment_policy_parameters/main.py", line 42, in run
    valid_data["order_moment"] = valid_data.apply(
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/core/frame.py", line 7768, in apply
    return op.get_result()
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/opt/conda/default/lib/python3.8/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/opt/conda/default/lib/python3.8/site-packages/replenishment_policy_parameters/main.py", line 43, in <lambda>
    lambda x: calculate_order_moment(
  File "/opt/conda/default/lib/python3.8/site-packages/replenishment_policy/decorators.py", line 14, in catch_invalid_values_wrapper
    return func(*args, **kwargs)
  File "/opt/conda/default/lib/python3.8/site-packages/replenishment_policy/order_moment.py", line 44, in calculate_order_moment
    julia = JuliaConnection()
  File "/opt/conda/default/lib/python3.8/site-packages/replenishment_policy/julia/julia.py", line 20, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/opt/conda/default/lib/python3.8/site-packages/replenishment_policy/julia/julia.py", line 74, in __init__
    from juliacall import Main  # Sets up a link to a Julia runtime
  File "/opt/conda/default/lib/python3.8/site-packages/juliacall/__init__.py", line 214, in <module>
    init()
  File "/opt/conda/default/lib/python3.8/site-packages/juliacall/__init__.py", line 143, in init
    CONFIG['exepath'] = exepath = juliapkg.executable()
  File "/opt/conda/default/lib/python3.8/site-packages/juliapkg/deps.py", line 296, in executable
    resolve()
  File "/opt/conda/default/lib/python3.8/site-packages/juliapkg/deps.py", line 241, in resolve
    exe, ver = find_julia(compat=compat, prefix=STATE['install'], install=True, upgrade=True)
  File "/opt/conda/default/lib/python3.8/site-packages/juliapkg/find_julia.py", line 80, in find_julia
    bestcompat = Compat.parse('=' + best_julia_version(compat)[0])
  File "/opt/conda/default/lib/python3.8/site-packages/juliapkg/install_julia.py", line 113, in best_julia_version
    vers = compatible_julia_versions(compat)
  File "/opt/conda/default/lib/python3.8/site-packages/juliapkg/install_julia.py", line 80, in compatible_julia_versions
    for (k, v) in all_julia_versions().items():
  File "/opt/conda/default/lib/python3.8/site-packages/juliapkg/install_julia.py", line 30, in all_julia_versions
    with urllib.request.urlopen(url) as fp:
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/default/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
</code>

**Comment by pberi** [comment]
@DilumAluthge @staticfloat could you please elaborate further? Since I have zero understanding of how mirroring works.

**Comment by pberi** [comment]
Sorry, I re-read your message @DilumAluthge and I get it now that it's fixed from your end. Case closed!
